### PR TITLE
Restrict youtube assets to ones in the Guardian's ownership.

### PR DESCRIPTION
**Pull request by akash1810**
Adds a restriction allowing only youtube videos that we own to be added as an asset as only our content should be atoms.

not-gu

### CODE REVIEW

**Comment by kelvin-chappell** [comment]
Doesn't this mean hosted video atoms won't work?
eg. https://www.theguardian.com/advertiser-content/explore-canada-food-busker-in-canada/duelling-bagels

**Comment by akash1810** [comment]
@kelvin-chappell shoot yeah! Will update to only do this validation when `Category != Hosted`

**Comment by akash1810** [comment]
[Updated](https://github.com/guardian/media-atom-maker/pull/144/commits/9661d08a1e13b270bd0e28e1c29a82e2dee3f22e) now @kelvin-chappell

**Comment by kelvin-chappell** [comment]
👍  Thanks!

**Pull request merged**
