### PR TITLE
tabbed ui

### PR DESCRIPTION
**Pull request by akash1810**
mam-tabs

### CODE REVIEW

**Comment by sihil** [comment]
The `ice cream` commit seems not to have anything related to ice-cream. Can you push the changes back into the appropriate previous commits - or at the least give it a more descriptive commit?

**Comment by sihil** [comment]
Is a tabbed UI better? Was this a user or UX request? What's the background on the piece of work?

**Comment by akash1810** [comment]
> The `ice cream` commit seems not to have anything related to ice-cream. Can you push the changes back into the appropriate previous commits - or at the least give it a more descriptive commit?

I thought no-one would notice this 😂 Its a WIP commit TBH (wip -> wippy -> ice cream).

> Is a tabbed UI better? Was this a user or UX request?

Yes to both. We've been asked to introduce some more fields in the form. The first pass of doing this (just adding it to the current form) looked really cluttered and confusing. After a chat with UX, we agreed that a tabbed UI makes more sense as we can group fields logically across tabs.

> given that it's a large commit, can you give a bit of guidance to the reviewer so they know where to start looking?

👍 I tried to make each commit (other than ice cream) independently reviewable (arguably they should be PRs in the own right). I'll tidy this PR up for clarity - raising multiple small PRs rather than one massive one. Thanks for keeping me honest!

**Comment by akash1810** [comment]
This has been split out into multiple PRs to keep a small surface of change in each.

Closing this PR.

**Pull request closed without merging**
