### PR TITLE
Delete teamcity.sh

### PR DESCRIPTION
**Pull request by tjsilver**
## What does this change?

Following from #1007, this PR removes the old `teamcity.sh` script which has been replaced by the three separate scripts.

### CODE REVIEW

**Comment by akash1810** [comment]
I'd strongly advocate to keeping a single CI script as it makes it that much easier to reproduce CI issues locally, in that you just run the one file rather than remembering which files CI is running and in which order.

Rather than delete `teamcity.sh` I'd suggest updating it to call out to the other scripts added in #1007 ,

**Comment by tjsilver** [comment]
> I'd strongly advocate for keeping a single CI script as it makes it that much easier to reproduce CI issues locally, in that you just run the one file rather than remembering which files CI is running and in which order.
> 
> Rather than delete `teamcity.sh` I'd suggest updating it to call out to the other scripts added in #1007 and continue to have CI execute `teamcity.sh` only.

That sounds sensible, will do that 👍

**Comment by tjsilver** [comment]
Closing and will create another PR with the updated single `teamcity.sh` script.

**Comment by AWare** [comment]
Putting them in individual scripts allows each build step to run in its own docker environment and means we don't have to mess around with nvm on teamcity. While you're right that this makes it slightly harder to run the ci process locally- this issue is also present in all similar github actions builds and has not presented an impediment to its takeup.

**Review by twrichards — APPROVED** [review]

**Pull request merged**
